name: JFrog CI Demo

on:
  push:
    branches:
      - main

env:
  # Define common environment variables
  JAVA_VERSION: 17
  PROJECT_NAME: 'springboot-task-tracker-h2-api'
  DOCKERFILE_PATH: 'docker/Dockerfile'
  JFROG_DOCKER_REPO: 'spring-demo-docker-appimages'
  JFROG_MAVEN_REPO: 'spring-maven-apps-repository'          

jobs:
  # Job 1: Build jar, Docker Image and execute Unit Tests
  test_and_build:
    runs-on: ubuntu-latest
    outputs:
      jaf_file_name: ${{ steps.get-jar-name.outputs.jar_name }}
      docker_image_tag: ${{ steps.get-tag-name.outputs.docker_tag }}
      project_version: ${{ steps.get-version.outputs.project_version }}

    steps:
        - name: Checkout Code
          uses: actions/checkout@v4
        
        - name: Set up Java ${{ env.JAVA_VERSION }}
          uses: actions/setup-java@v4
          with:
              distribution: 'temurin'
              java-version: ${{ env.JAVA_VERSION }}
              cache: 'maven'

        - name: Get Maven Project Version
          id: get-version
          run: |
            PROJECT_VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
            echo "project_version=$PROJECTVSION" >> $GITHUB_OUTPUT
            echo "Discovered project version: $PROJECT_VERSION"

        - name: Build Maven Project and Get JAR Name
          id: get-jar-name
          run: |
            mvn clean package -DskipTests #Build without test run in the next step
            JAR_NAME=$(ls target/*.jar | head -n 1 | xargs -n 1 basename )
            echo "jar_name=$JAR_NAME" >> "$GITHUB_OUTPUT"
            echo "Discovered JAR name: $JAR_NAME"

        - name: Execute Unit Test
          run: mvn test
          env:
            MAVEN_OPTS: -Dmaven.wagon.http.pool=false -Dmaven.wagon.http.retryHandler.count=3

        - name: Upload JAR Artifact
          uses: actions/upload-artifact@v4
          if: ${{ success()}}
          with:
            name: ${{ env.PROJECT_NAME }}-jar
            path: target/${{ steps.get-jar-name.outputs.jar_name }}
            retention-days: 7    

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Build Docker Image
          id: build-image
          uses: docker/build-push-action@v5
          with:
            context: .
            file: ${{ env.DOCKERFILE_PATH }}
            push: false # Only build locally
            load: true # Load the image into Docker
            tags: ${{ env.PROJECT_NAME }}:${{ github.sha }}

        - name: Get docker tag name
          id: get-tag-name
          run: |
            TAG_NAME="${{ env.PROJECT_NAME }}:${{ github.sha }}"
            echo "docker_tag=$TAG_NAME" >> "$GITHUB_OUTPUT"
            echo "TAG_NAME is $TAG_NAME"


        - name: List Docker Images
          run: docker images    
          

        - name: Export Docker Image to Tar (for subsequent jobs)
          run: docker save ${{ env.PROJECT_NAME }}:${{ github.sha}} -o ${{ env.PROJECT_NAME}}.tar

        - name: Upload Docker Image Tarball Artifact
          uses: actions/upload-artifact@v4
          if: ${{ success() }}
          with:
            name: ${{ env.PROJECT_NAME }}-docker-image
            path: ${{ env.PROJECT_NAME }}.tar
            retention-days: 7

  # Job 2: Deploy Artifacts (Runs only after all prior jobs succed)
  store_artifacts:
    runs-on: ubuntu-latest
    needs:  #This job depends on ALL preceding funcional groups
      - test_and_build

    steps:
      - name: Download JAR Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-jar
          path: ./downloaded-artifacts/jar/

      - name: Download Docker Image Tarball Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.PROJECT_NAME }}-docker-image
          path: ./downloaded-artifacts/docker-image/

      - name: List Downloaded Artifacts
        run: |
          echo "Downloaded JAR files:"
          ls ./downloaded-artifacts/jar/
          echo "Downloaded Docker image tarballs:"
          ls ./downloaded-artifacts/docker-image/

      - name: Log in to JFrog Artifactory Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.JFROG_DEMO_REGISTRY }}
          username: ${{ secrets.JFROG_DEMO_USERNAME }}
          password: ${{ secrets.JFROG_DEMO_PASSWORD }}

          
      - name: Load Docker Image and Tag
        run: |
          docker load -i ./downloaded-artifacts/docker-image/${{ env.PROJECT_NAME}}.tar
          # Re-tag the image with the full JFrog repository path
          docker images
          docker tag ${{ needs.test_and_build.outputs.docker_image_tag }} ${{ secrets.JFROG_DEMO_REGISTRY }}/${{ env.JFROG_DOCKER_REPO}}/${{ needs.test_and_build.outputs.docker_image_tag }}
          docker tag ${{ needs.test_and_build.outputs.docker_image_tag }} ${{ secrets.JFROG_DEMO_REGISTRY }}/${{ env.JFROG_DOCKER_REPO}}/${{ env.PROJECT_NAME}}:latest
          echo "Verifying the new tags"
          docker images

      - name: Push Docker Image to JFrog Artifactory
        run: |
          docker push ${{ secrets.JFROG_DEMO_REGISTRY }}/${{ env.JFROG_DOCKER_REPO}}/${{ needs.test_and_build.outputs.docker_image_tag }}   
          docker push ${{ secrets.JFROG_DEMO_REGISTRY }}/${{ env.JFROG_DOCKER_REPO}}/${{ env.PROJECT_NAME}}:latest